/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Bobby
 */
public class ComptePanel extends javax.swing.JPanel {

    /**
     * Creates new form ComptePanel
     */
    public ComptePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoClientPanel = infoClientPanel = new GUI.InfoClientPanel(true);
        historiquePanel = new javax.swing.JPanel();
        jlblHistorique = new javax.swing.JLabel();
        jscpHistorique = new javax.swing.JScrollPane();
        jtblHistorique = new javax.swing.JTable();

        historiquePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        historiquePanel.setMinimumSize(new java.awt.Dimension(400, 400));
        historiquePanel.setPreferredSize(new java.awt.Dimension(400, 400));

        jlblHistorique.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHistorique.setText("Historique des transactions");

        jtblHistorique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Type", "Titre", "Prix", "Date de retour"
            }
        ));
        jscpHistorique.setViewportView(jtblHistorique);

        javax.swing.GroupLayout historiquePanelLayout = new javax.swing.GroupLayout(historiquePanel);
        historiquePanel.setLayout(historiquePanelLayout);
        historiquePanelLayout.setHorizontalGroup(
            historiquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historiquePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(historiquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscpHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addContainerGap())
        );
        historiquePanelLayout.setVerticalGroup(
            historiquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historiquePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblHistorique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoClientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historiquePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historiquePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoClientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel historiquePanel;
    private GUI.InfoClientPanel infoClientPanel;
    private javax.swing.JLabel jlblHistorique;
    private javax.swing.JScrollPane jscpHistorique;
    private javax.swing.JTable jtblHistorique;
    // End of variables declaration//GEN-END:variables
}
