/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Bobby
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        locationPanel = new GUI.LocationPanel();
        achatPanel = new GUI.AchatPanel();
        comptePanel = new GUI.ComptePanel();
        inventairePanel = new GUI.InventairePanel();
        adminPanel = new GUI.AdminPanel();
        tabsPanel = new javax.swing.JPanel();
        jtbLocationTab = new javax.swing.JToggleButton();
        jtbAchatTab = new javax.swing.JToggleButton();
        jtbInventaireTab = new javax.swing.JToggleButton();
        jtbCompteTab = new javax.swing.JToggleButton();
        jtbAdminTab = new javax.swing.JToggleButton();
        jMenuBar = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();
        jmEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 540));
        setPreferredSize(new java.awt.Dimension(1000, 540));

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(locationPanel, "location");
        mainPanel.add(achatPanel, "achat");
        mainPanel.add(comptePanel, "compte");
        mainPanel.add(inventairePanel, "inventaire");
        mainPanel.add(adminPanel, "admin");

        Tabs.add(jtbLocationTab);
        jtbLocationTab.setSelected(true);
        jtbLocationTab.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder));
        jtbLocationTab.setFocusable(false);
        jtbLocationTab.setLabel("Location de film");
        jtbLocationTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbLocationTabActionPerformed(evt);
            }
        });

        Tabs.add(jtbAchatTab);
        jtbAchatTab.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder));
        jtbAchatTab.setFocusable(false);
        jtbAchatTab.setLabel("Achat de produit");
        jtbAchatTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbAchatTabActionPerformed(evt);
            }
        });

        Tabs.add(jtbInventaireTab);
        jtbInventaireTab.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder));
        jtbInventaireTab.setFocusable(false);
        jtbInventaireTab.setLabel("Inventaire");
        jtbInventaireTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbInventaireTabActionPerformed(evt);
            }
        });

        Tabs.add(jtbCompteTab);
        jtbCompteTab.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder));
        jtbCompteTab.setFocusable(false);
        jtbCompteTab.setLabel("Paramètres compte");
        jtbCompteTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbCompteTabActionPerformed(evt);
            }
        });

        Tabs.add(jtbAdminTab);
        jtbAdminTab.setText("Administration");
        jtbAdminTab.setActionCommand("");
        jtbAdminTab.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder));
        jtbAdminTab.setFocusable(false);
        jtbAdminTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbAdminTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabsPanelLayout = new javax.swing.GroupLayout(tabsPanel);
        tabsPanel.setLayout(tabsPanelLayout);
        tabsPanelLayout.setHorizontalGroup(
            tabsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbLocationTab, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbAchatTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbInventaireTab, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbCompteTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jtbAdminTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        tabsPanelLayout.setVerticalGroup(
            tabsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jtbLocationTab, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtbAchatTab, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtbInventaireTab, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtbCompteTab, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtbAdminTab, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jmFile.setText("File");

        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmFile.add(jmiExit);

        jMenuBar.add(jmFile);

        jmEdit.setText("Edit");
        jMenuBar.add(jmEdit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbLocationTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbLocationTabActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "location");
    }//GEN-LAST:event_jtbLocationTabActionPerformed

    private void jtbAchatTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbAchatTabActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "achat");
    }//GEN-LAST:event_jtbAchatTabActionPerformed

    private void jtbInventaireTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbInventaireTabActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "inventaire");
    }//GEN-LAST:event_jtbInventaireTabActionPerformed

    private void jtbCompteTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbCompteTabActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "compte");
    }//GEN-LAST:event_jtbCompteTabActionPerformed

    private void jtbAdminTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbAdminTabActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "admin");
    }//GEN-LAST:event_jtbAdminTabActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        dispose();
    }//GEN-LAST:event_jmiExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Tabs;
    private GUI.AchatPanel achatPanel;
    private GUI.AdminPanel adminPanel;
    private GUI.ComptePanel comptePanel;
    private GUI.InventairePanel inventairePanel;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jmEdit;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JToggleButton jtbAchatTab;
    private javax.swing.JToggleButton jtbAdminTab;
    private javax.swing.JToggleButton jtbCompteTab;
    private javax.swing.JToggleButton jtbInventaireTab;
    private javax.swing.JToggleButton jtbLocationTab;
    private GUI.LocationPanel locationPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel tabsPanel;
    // End of variables declaration//GEN-END:variables
}
